version: "2"

services:
  crdb:
    container_name: crdb
    hostname: crdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --cluster-name=example-single-node --logtostderr=WARNING --log-file-verbosity=WARNING --insecure
    ports:
      - "26257:26257"
      - "8081:8080"

  crdb-init:
    container_name: crdb-init
    hostname: crdb-init
    image: timveil/cockroachdb-remote-client:latest
    environment:
      - COCKROACH_HOST=crdb:26257
      - COCKROACH_INSECURE=true
      - DATABASE_NAME=genie
    depends_on:
      - crdb

  genie:
    build: genie
    ports:
      - "8080:8080"
    depends_on:
      - genie-hadoop-prod
      - genie-hadoop-test
      - genie-apache
      - crdb
    tty: true
    container_name: genie_demo_app_3.3.20

  genie-apache:
    image: netflixoss/genie-demo-apache:3.3.20
    tty: true
    container_name: genie_demo_apache_3.3.20

  genie-client:
    image: netflixoss/genie-demo-client:3.3.20
    depends_on:
      - genie
    tty: true
    container_name: genie_demo_client_3.3.20

  genie-hadoop-prod:
    image: sequenceiq/hadoop-docker:2.7.1
    command: /bin/bash -c "/usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver && /etc/bootstrap.sh -bash"
    ports:
      - "19888:19888"
      - "50070:50070"
      - "50075:50075"
      - "8088:8088"
    tty: true
    container_name: genie_demo_hadoop_prod_3.3.20

  genie-hadoop-test:
    image: sequenceiq/hadoop-docker:2.7.1
    command: /bin/bash -c "/usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver && /etc/bootstrap.sh -bash"
    ports:
      - "19889:19888"
      - "50071:50070"
      - "50076:50075"
      - "8089:8088"
    tty: true
    container_name: genie_demo_hadoop_test_3.3.20
