version: '3.5'

networks:
  shared:
    driver: bridge
  east:
    driver: bridge
  central:
    driver: bridge
  west:
    driver: bridge

services:

  east-1:
    container_name: east-1
    hostname: east-1
    image: cockroachdb/cockroach:v2.1.4
    networks:
      - shared
      - east
    command: start --logtostderr --insecure --locality=datacenter=east
    ports:
      - 8001:8080
      - 9001:26257

  east-2:
    container_name: east-2
    hostname: east-2
    image: cockroachdb/cockroach:v2.1.4
    networks:
      - shared
      - east
    command: start --logtostderr --insecure --locality=datacenter=east --join=east-1
    ports:
      - 8002:8080
      - 9002:26257
    depends_on:
      - east-1

  east-3:
    container_name: east-3
    hostname: east-3
    image: cockroachdb/cockroach:v2.1.4
    networks:
      - shared
      - east
    command: start --logtostderr --insecure --locality=datacenter=east --join=east-1
    ports:
      - 8003:8080
      - 9003:26257
    depends_on:
      - east-2


  central-1:
    container_name: central-1
    hostname: central-1
    image: cockroachdb/cockroach:v2.1.4
    networks:
      - shared
      - central
    command: start --logtostderr --insecure --locality=datacenter=central --join=east-1
    ports:
      - 8004:8080
      - 9004:26257
    depends_on:
      - east-3

  central-2:
    container_name: central-2
    hostname: central-2
    image: cockroachdb/cockroach:v2.1.4
    networks:
      - shared
      - central
    command: start --logtostderr --insecure --locality=datacenter=central --join=east-1
    ports:
      - 8005:8080
      - 9005:26257
    depends_on:
      - central-1

  central-3:
    container_name: central-3
    hostname: central-3
    image: cockroachdb/cockroach:v2.1.4
    networks:
      - shared
      - central
    command: start --logtostderr --insecure --locality=datacenter=central --join=east-1
    ports:
      - 8006:8080
      - 9006:26257
    depends_on:
      - central-2


  west-1:
    container_name: west-1
    hostname: west-1
    image: cockroachdb/cockroach:v2.1.4
    networks:
      - shared
      - west
    command: start --logtostderr --insecure --locality=datacenter=west --join=east-1
    ports:
      - 8007:8080
      - 9007:26257
    depends_on:
      - central-3

  west-2:
    container_name: west-2
    hostname: west-2
    image: cockroachdb/cockroach:v2.1.4
    networks:
      - shared
      - west
    command: start --logtostderr --insecure --locality=datacenter=west --join=east-1
    ports:
      - 8008:8080
      - 9008:26257
    depends_on:
      - west-1

  west-3:
    container_name: west-3
    hostname: west-3
    image: cockroachdb/cockroach:v2.1.4
    networks:
      - shared
      - west
    command: start --logtostderr --insecure --locality=datacenter=west --join=east-1
    ports:
      - 8009:8080
      - 9009:26257
    depends_on:
      - west-2
